// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// Only load dotenv in development (not in Docker where env vars are set directly)
if (process.env.NODE_ENV !== "production") {
  require("dotenv/config");
}
import { defineConfig } from "prisma/config";

const databaseUrl = process.env["DATABASE_URL"];

if (!databaseUrl) {
  throw new Error("DATABASE_URL environment variable is not set");
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: databaseUrl,
  },
});
